import React from "react";
let MyData = [
{ Std_id: 1,     Std_name: "Rahul",              Std_age: 13, Std_class: 10, Std_place:"Ameerpet",Std_grd:"A",Std_marks:90 },
{ Std_id: 2,     Std_name: "Arvind",              Std_age: 14, Std_class:10, Std_place:"Malkagjgiri",Std_grd:"B",Std_marks:77 },
{ Std_id: 3,     Std_name: "Surya",              Std_age: 15, Std_class: 10, Std_place:"Safilguda",Std_grd:"C",Std_marks:72},
{ Std_id: 4,     Std_name: "Kumar",              Std_age: 13, Std_class: 10, Std_place:"Tarnaka",Std_grd:"D",Std_marks:50},
{ Std_id: 5,     Std_name: "Sunil",              Std_age: 13, Std_class: 10, Std_place:"Ameerpet",Std_grd:"A",Std_marks:99},
{ Std_id: 6,     Std_name: "Ajay",               Std_age: 13, Std_class: 10, Std_place:"Begumpet",Std_grd:"B",Std_marks:76},
{ Std_id: 7,     Std_name: "Prabhu",              Std_age: 15, Std_class:10, Std_place:"Malkagjgiri",Std_grd:"C",Std_marks:66},
{ Std_id: 8,     Std_name: "Shreya",              Std_age: 14, Std_class:10, Std_place:"Ameerpet",Std_grd:"D",Std_marks:47 },
{ Std_id: 9,     Std_name: "Kavya",              Std_age: 13, Std_class: 10, Std_place:"Ameerpet",Std_grd:"A",Std_marks:88 },
{ Std_id: 10,     Std_name: "Aishu",              Std_age: 13, Std_class:10, Std_place:"Begumpeet",Std_grd:"A" ,Std_marks:89 },
{Std_id:"0112022" , Std_name:"Raghu",             Std_age:14 , Std_class:9   , Std_grd:"D" ,  Std_place:"SR Nagar" ,Std_marks:50} ,
{Std_id:"0122022" , Std_name:"Ramya",             Std_age:15 , Std_class:9   , Std_grd:"C" ,  Std_place:"SR Nagar" ,Std_marks:60 },
{Std_id:"0132022" , Std_name:"Venkatesh",         Std_age:14 , Std_class:9   , Std_grd:"F" ,  Std_place:"SR Nagar" ,Std_marks:45  },
{Std_id:"0142022" , Std_name:"Sai Prasad",        Std_age:14 , Std_class:9   , Std_grd:"A" ,  Std_place:"SR Nagar" ,Std_marks:95  },
{Std_id:"0152022" , Std_name:"Sai",               Std_age:13 , Std_class:9   , Std_grd:"A" ,  Std_place:"SR Nagar" ,Std_marks:98},
{Std_id:"0162022" , Std_name:"Vinay",             Std_age:15 , Std_class:9   , Std_grd:"A" ,  Std_place:"SR Nagar" ,Std_marks:85  },
{Std_id:"0172022" , Std_name:"Vijay",             Std_age:16 , Std_class:9   , Std_grd:"C" ,  Std_place:"SR Nagar" ,Std_marks:60  },
{Std_id:"0182022" , Std_name:"Sharukhh",          Std_age:14 , Std_class:9   , Std_grd:"B" ,  Std_place:"SR Nagar" ,Std_marks:78  },
{Std_id:"0192022" , Std_name:"Ahmad",             Std_age:15 , Std_class:9   , Std_grd:"D" ,  Std_place:"SR Nagar" ,Std_marks:55 },
{Std_id:"0202022" , Std_name:"Nagaraj",           Std_age:14 , Std_class:9   , Std_grd:"A" ,  Std_place:"SR Nagar" ,Std_marks:88  },
{Std_id:"0212022" , Std_name:"Giri",              Std_age:15 , Std_class:9   , Std_grd:"A" ,  Std_place:"SR Nagar" ,Std_marks:88  },
{Std_id:"0222022" , Std_name:"Malathi",           Std_age:16 , Std_class:9   , Std_grd:"F" ,  Std_place:"SR Nagar" ,Std_marks:42 },
{Std_id:"0232022" , Std_name:"Pavani",            Std_age:14 , Std_class:9   , Std_grd:"B" ,  Std_place:"SR Nagar" ,Std_marks:80 },
{Std_id:"0242022" , Std_name:"Sanjana",           Std_age:15 , Std_class:9   , Std_grd:"C" ,  Std_place:"SR Nagar" ,Std_marks:63 },
{Std_id:"0252022" , Std_name:"Lakshmi",           Std_age:13 , Std_class:9   , Std_grd:"D" ,  Std_place:"SR Nagar" ,Std_marks:53 },
{Std_id:"0262022" , Std_name:"sunil Kumar",       Std_age:14 , Std_class:8   , Std_grd:"A" ,  Std_place:"Madhuran" ,Std_marks:99 },         
{Std_id:"0272022" , Std_name:"Haripavan",         Std_age:13 , Std_class:8   , Std_grd:"A" ,  Std_place:"Ameerpet" ,Std_marks: 91 },     
{Std_id:"0282022" , Std_name:"Abhishek",          Std_age:14 , Std_class:8   , Std_grd:"A" ,  Std_place:"S.R Nagar" , Std_marks:99},     
{Std_id:"0292022" , Std_name:"Chandhu",           Std_age:13 , Std_class:8   , Std_grd:"A" ,  Std_place:"L.B Nagar" ,Std_marks:99},     
{Std_id:"0302022" , Std_name:"Shravan",           Std_age:12,  Std_class:8   , Std_grd:"A" ,  Std_place:"Hitec City" ,Std_marks:93},     
{Std_id:"0312022" , Std_name:"Bhuvneshwar",       Std_age:13,  Std_class:8   , Std_grd:"A" ,  Std_place:"Moosapet" ,Std_marks:89},     
{Std_id:"0322022" , Std_name:"Natrajan",          Std_age:14 , Std_class:8   , Std_grd:"B" ,  Std_place:"Borabanda",Std_marks:77},     
{Std_id:"0332022" , Std_name:" Rahaman",          Std_age:13 , Std_class:8   , Std_grd:"B" ,  Std_place:"Balkampet" ,Std_marks:76},     
{Std_id:"0342022" , Std_name:"Schith",            Std_age:14 , Std_class:8   , Std_grd:"B" ,  Std_place:"Ameerprt"  ,Std_marks:83},     
{Std_id:"0352022" , Std_name:"Tripathi",          Std_age:13 , Std_class:8   , Std_grd:"C" ,  Std_place:"S.R Nagar" ,Std_marks:67},     
{Std_id:"0362022" , Std_name:"Shashank",          Std_age:14 , Std_class:8   , Std_grd:"C" ,  Std_place:"L.B Nagar" ,Std_marks:69 },     
{Std_id:"0372022" , Std_name:"Karthik",           Std_age:13 , Std_class:8   , Std_grd:"D" ,  Std_place:"Moosapet"   ,Std_marks:53},     
{Std_id:"0382022" , Std_name:"Umran Malik",       Std_age:13 , Std_class:8   , Std_grd:"D" ,  Std_place:"Borabanda" ,Std_marks:52},     
{Std_id:"0392022" , Std_name:"Mahesh Babu",       Std_age:13 , Std_class:8   , Std_grd:"D" ,  Std_place:"Balkampet"   ,Std_marks:57},     
{Std_id:"0402022" , Std_name:"Tharun",            Std_age:12 , Std_class:8   , Std_grd:"F" ,  Std_place:"Hitec City" ,Std_marks:43 },
{Std_id:"0422022" , Std_name:"Dhoni" ,            Std_age:13 , Std_class:6   , Std_grd:"F" ,  Std_place:"Sanathanagar " ,Std_marks:42},
{Std_id:"0432022" , Std_name:"Smriti" ,           Std_age:13 , Std_class:6   , Std_grd:"A" ,  Std_place:"Kachiguda ",Std_marks:99},
{Std_id:"0442022" , Std_name:"Kour" ,             Std_age:12 , Std_class:6   , Std_grd:"A" ,  Std_place:"Uppal ",Std_marks:90},
{Std_id:"0452022" , Std_name:"Rohit" ,            Std_age:12 , Std_class:6   , Std_grd:"A" ,  Std_place:"Panjagutta ",Std_marks:91},
{Std_id:"0412022" , Std_name:"Virat" ,            Std_age:12 , Std_class:6   , Std_grd:"B" ,  Std_place:"Khairatabad ",Std_marks:77},
{Std_id:"0462022" , Std_name:"Sachin" ,           Std_age:12 , Std_class:6   , Std_grd:"B" ,  Std_place:"Sanathnagar ",Std_marks:79},
{Std_id:"0472022" , Std_name:"Raina" ,            Std_age:13 , Std_class:6   , Std_grd:"C" ,  Std_place:"Khairathabad ",Std_marks:62},
{Std_id:"0482022" , Std_name:"Mithali" ,          Std_age:12 , Std_class:6   , Std_grd:"C" ,  Std_place:"Uppal ",Std_marks:69},
{Std_id:"0492022" , Std_name:"Chahar" ,           Std_age:13 , Std_class:6   , Std_grd:"C" ,  Std_place:"Khairatabad ",Std_marks:67},
{Std_id:"0502022" , Std_name:"Ravindra" ,         Std_age:12 , Std_class:6   , Std_grd:"C" ,  Std_place:"Kachiguda ",Std_marks:63},
{Std_id:"0512022" , Std_name:"navya",             Std_age:13 , Std_class:7   , Std_grd:"C" ,  Std_place:" Karimnagar",Std_marks:62},
{Std_id:"0522022" , Std_name:" siri",             Std_age:13 , Std_class:7   , Std_grd:"F" ,  Std_place:" Kachiguda",Std_marks:33},
{Std_id:"0532022" , Std_name:" shivani",          Std_age:12 , Std_class:7   , Std_grd:"F" ,  Std_place:"Kbhpcolony",Std_marks:42},
{Std_id:"0542022" , Std_name:" surya",            Std_age:12 , Std_class:7   , Std_grd:"A" ,  Std_place:" Kbhpcolony",Std_marks:97},
{Std_id:"0552022" , Std_name:" teju",             Std_age:12 , Std_class:7   , Std_grd:"B" ,  Std_place:" Hi-techcity",Std_marks:77},
{Std_id:"0562022" , Std_name:"sandhya ",          Std_age:13 , Std_class:7   , Std_grd:"B" ,  Std_place:" Madhapur",Std_marks:79},
{Std_id:"0572022" , Std_name:" chanti",           Std_age:11 , Std_class:7   , Std_grd:"C" ,  Std_place:" punjagutta",Std_marks:69},
{Std_id:"0582022" , Std_name:" sahithi",          Std_age:14 , Std_class:7   , Std_grd:"C" ,  Std_place:" Jagtial",Std_marks:68},
{Std_id:"0592022" , Std_name:" sri laxmi",        Std_age:12 , Std_class:7   , Std_grd:"B" ,  Std_place:" Hyderabad",Std_marks:78},
{Std_id:"0602022" , Std_name:"selfie",            Std_age:13 , Std_class:7   , Std_grd:"F" ,  Std_place:" Kphp",Std_marks:42}
]
export default MyData
